# Generated by Django 4.2.13 on 2024-05-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClaimReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(verbose_name="dane dotyczące reklamacji")),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="nazwa firmy"
                    ),
                ),
                ("nip", models.IntegerField(blank=True, verbose_name="NIP")),
                ("name", models.CharField(max_length=15, verbose_name="imie")),
                ("surname", models.CharField(max_length=35, verbose_name="nazwisko")),
                ("tel_number", models.IntegerField(verbose_name="numer telefonu")),
                ("email", models.EmailField(max_length=50, verbose_name="adres email")),
                (
                    "claim_report_type",
                    models.CharField(
                        choices=[
                            ("jakościowa", "Jakościowa"),
                            ("ilościowa", "Ilościowa"),
                            ("finansowa", "Finansowa"),
                            ("inna", "Inna"),
                        ],
                        max_length=10,
                        verbose_name="rodzaj reklamacji",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=15, verbose_name="numer faktury"),
                ),
                ("product", models.CharField(max_length=15, verbose_name="towar")),
                ("quantity", models.IntegerField(verbose_name="ilosc")),
                (
                    "claim_report_client_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="numer reklamacji klienta",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=2048, verbose_name="opis"),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True, upload_to="uploads/", verbose_name="pliki"
                    ),
                ),
            ],
        ),
    ]
