# Generated by Django 4.2.13 on 2024-05-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0002_remove_claimreport_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimreport",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="pobrane"),
        ),
    ]
