# Generated by Django 4.2.13 on 2024-05-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0003_claimreport_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimreport",
            name="archive",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="archives/",
                verbose_name="zipped attachments",
            ),
        ),
    ]
