# Generated by Django 4.2.13 on 2024-05-17 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0004_claimreport_archive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimreport",
            name="attachments",
        ),
    ]
