# Generated by Django 4.2.13 on 2024-05-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0005_remove_claimreport_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimreport",
            name="claim_report_type",
            field=models.CharField(
                choices=[
                    (1, "Jakościowa"),
                    (2, "Ilościowa"),
                    (3, "Finansowa"),
                    (4, "Inna"),
                ],
                max_length=10,
                verbose_name="rodzaj reklamacji",
            ),
        ),
    ]
