# Generated by Django 4.2.13 on 2024-05-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0006_alter_claimreport_claim_report_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimreport",
            name="claim_report_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Jakościowa"),
                    (2, "Ilościowa"),
                    (3, "Finansowa"),
                    (4, "Inna"),
                ],
                verbose_name="rodzaj reklamacji",
            ),
        ),
    ]
