# Generated by Django 4.2.13 on 2024-05-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0007_alter_claimreport_claim_report_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimreport",
            name="nip",
            field=models.CharField(blank=True, max_length=13, verbose_name="NIP"),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="tel_number",
            field=models.CharField(max_length=30, verbose_name="numer telefonu"),
        ),
    ]
