# Generated by Django 4.2.13 on 2024-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0008_alter_claimreport_nip_alter_claimreport_tel_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimreport",
            name="claim_report_client_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Customer Complaint Number"
            ),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="claim_report_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Qualitative"),
                    (2, "Quantitative"),
                    (3, "Financial"),
                    (4, "Other"),
                ],
                verbose_name="Type of Complaint",
            ),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Company Name"
            ),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="description",
            field=models.TextField(
                blank=True, max_length=2048, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="email",
            field=models.EmailField(max_length=50, verbose_name="E-mail Address"),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="invoice_number",
            field=models.CharField(max_length=15, verbose_name="Invoice Number"),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="name",
            field=models.CharField(max_length=15, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="nip",
            field=models.CharField(
                blank=True, max_length=13, verbose_name="Tax Identification Number"
            ),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="Processed"),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="product",
            field=models.CharField(
                max_length=15, verbose_name="Goods (symbol from the invoice)"
            ),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="quantity",
            field=models.IntegerField(verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="surname",
            field=models.CharField(max_length=35, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="claimreport",
            name="tel_number",
            field=models.CharField(max_length=30, verbose_name="Phone Number"),
        ),
    ]
