# Generated by Django 4.2.13 on 2024-05-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0009_alter_claimreport_claim_report_client_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimreport",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Quantity"
            ),
        ),
    ]
